### ISSUE TITLE
how long HAS Illinois been without a budget?

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#10]
I've clicked on about 10 news articles & legitimately did not see a date anywhere. halp

**Comment by onlymattjohnson** [comment]
I think this was at the start of the fiscal year, so since 7/1/2015

**Comment by cathydeng** [comment]
thx @itstriz! do you have a source we can cite?

**Comment by onlymattjohnson** [comment]
Sure.  Here's what I've found.  

[New York Times - One State’s Struggle to Make Ends Meet: Why Illinois Is Without a Budget](http://www.nytimes.com/2015/10/27/us/illinois-budget-stalemate-rauner-and-democrats-divided.html?_r=0):

> Lawmakers were deadlocked in negotiations leading up to the budget deadline of July 1, the beginning of the fiscal year.

[Huffington Post - The Unfortunate Effects of Illinois' Budget Crisis](http://www.huffingtonpost.com/reboot-illinois/the-unfortunate-effects-o_b_8972912.html):

> By law, an Illinois budget for fiscal year 2016 should have been passed no later than July 1, 2015.

[KMOV - No sign of an Illinois budget as state lawmakers take weekend off](http://www.kmov.com/story/29467287/no-sign-of-an-illinois-budget-as-lawmakers-take-weekend-off):

> Illinois lawmakers are on vacation and the state continues to operate without a budget, two days after the start of a new fiscal year. (published 7/2/2015)

**Comment by cathydeng** [comment]
thank you! :+1:

**Comment by cathydeng** [comment]
http://www.rebootillinois.com/2016/01/08/top-lists/rebootil/think-the-illinois-budget-crisis-isnt-having-an-effect-then-you-need-to-see-this/51102/

where does the time on this clock come from?

**Comment by renemarcelo** [comment]
@cathydeng http://www.tickcounter.com/countup/1435744800000/america-chicago/dhms/FFFFFF0D05E9000000FF0000/Time_without_an_Illinois_budget:?utm_source=widget&utm_medium=CountUp&utm_campaign=widget

**Comment by cathydeng** [comment]
ya it looks like it's counting up from 5am on july 1st. I'm wondering where the 5am comes from

**Comment by cathydeng** [comment]
whatever, just going with 5am, it's fine
