### ISSUE TITLE
content on what organizations have been affected

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#11]
drop links here

**Comment by derekeder** [comment]
http://capitolfax.com/2016/01/22/lssi-to-close-30-programs-eliminate-750-positions/

http://www.chicagotribune.com/news/ct-illinois-higher-education-funding-20160119-story.html

http://kwqc.com/2016/01/22/illinois-budget-impasse-to-force-intouch-adult-daycares-closure/

Map: http://m.huffpost.com/us/entry/the-unfortunate-effects-o_b_8972912.html

**Comment by onlymattjohnson** [comment]
Lutheran Social Services cuts 750 jobs http://www.chicagobusiness.com/article/20160122/NEWS07/160129931/big-lutheran-social-agency-cuts-750-jobs-amid-budget-impasse?X-IgnoreUserAgent=1

**Comment by onlymattjohnson** [comment]
Oh that's already on here.  Whoops

**Comment by derekeder** [comment]
Maybe we should call out some of the other consequences too, like:
- total number of jobs lost by shuttered organizations
- stalled government services
- long-term effects on state finances
- college students losing scholarships

Reboot Illinois does a good job calling these out: http://www.rebootillinois.com/2016/01/08/top-lists/rebootil/think-the-illinois-budget-crisis-isnt-having-an-effect-then-you-need-to-see-this/51102/

**Comment by hunterowens** [comment]
Hmm. Should we integrate these as reasons (see #15) or should we do what @derekeder suggests and add content like `Jobs Lost: x, Stalled Programs: y` etc.

**Comment by cathydeng** [comment]
i do love the idea of having a running counter of jobs lost, stalled programs, etc. but that info is hard to gather and would require continually researching & updating the site, which I don't want to commit to tbh. let's add them in as reasons for now.

**Comment by hunterowens** [comment]
Sounds pretty reasonable to me. 

Ok, I'll add these as reasons and we can close this.
