### ISSUE TITLE
brainstorm calls to action

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#13]

**Comment by kwritenow** [comment]
Ideas:
- share the clock to social media or email. twitter, facebook
- lookup to find your general assembly representatives, the governor
- autodial your general assembly representatives, the governor
- email or tweet your GA reps, governor
- share your story of being affected by the lack of a budget
- vote up some proposal that we offer. example: special session, or no benefits for reps until budget passed
- sign a petition
- take a poll or survey, view results

**Comment by cathydeng** [comment]
oooh I _really_ like 5 & 6! I'd hope that 1 is built in (that the website is clear & compelling enough that ppl want to share) & wouldn't want it to be the only action. I'm not super convinced that contacting representatives (2,3,4) is the most effective action, since representatives are often overloaded w/ messages from constituents and don't have good ways of filtering/listening.

**Comment by kwritenow** [comment]
If our CTA was to have folks share stories or vote up a proposed solution, how are you picturing that getting back to representatives and Rauner? Press coverage? Monitoring social media? What else? (making a list of things to look for later and see what seems to be effective)

**Comment by cathydeng** [comment]
i'm hoping press coverage, ya

**Comment by kwritenow** [comment]
What if people could upload photos of the impact this is having on them, or of them expressing their opinion about it?

What would this look like if it were an Instagram account? A Snapchat Discover story? A video game?

**Comment by kwritenow** [comment]
Would citizens and/or journalists be interested in seeing/joining conversation about it online? What if we hosted a twitter chat or AMA with some official or analyst or journalist and invited people to join?

**Comment by cathydeng** [comment]
I like both those ideas!

**Comment by kwritenow** [comment]
mad lib form letters to the editor, mad lib social media posts
budget crisis emojis
choose your own adventure: read more about X, Y, or Z

**Comment by kwritenow** [comment]
Have periodic meetups where we schedule time with Madigan and/or Chicago reps, invite users to come to the next one

**Comment by hunterowens** [comment]
Also add sample text for email the governor.

**Comment by nhutcheson** [comment]
Sample text for emailing the governor:
The time for ideological demands is gone, and now it's time to work with the legislature to pass a budget.

**Comment by cathydeng** [comment]
closed via https://github.com/chihacknight/il-budget-clock/commit/a32e4f56363b5a6643b5d49215e99b0a91a6dea6
