### ISSUE TITLE
running list of contributors to add to site acknowledgements

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#14]
Cathy Deng
Kristi Leach
Hunter Owens
Matt Johnson
Rene Marcelo
Derek Eder
Melanie Kruvelis
David Bild
Diana Hansen
Sarah Brune
Nate Hutcheson
Claire Micklin

**Comment by cathydeng** [comment]
@kwritenow what's your name?

**Comment by kwritenow** [comment]
@cathydeng Kristi Leach

**Comment by renemarcelo** [comment]
Rene M. Paccha (tentative), I will msg @cathydeng
