### ISSUE TITLE
get a URL

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#16]
@cathydeng @derekeder 
How does this usually work? Do y'all use the code on a free site like blogspot or wordpress? Does the group have a fund for retaining domain names?

**Comment by kwritenow** [comment]
ilbudgetclock dot com is available

**Comment by derekeder** [comment]
@kwritenow I can buy the domain and set it up.

re: names, I like ilbudgetclock - does what it says

**Comment by kwritenow** [comment]
Thanks. It was also available on Twitter: https://twitter.com/ILBudgetClock and Facebook https://www.facebook.com/IL-Budget-Clock-727226324079655/.

Having Twitter and Facebook presence would let us continue to share developments, background, etc without having to update the site, while doing double duty of bringing attention to the clock/issue.

I also set up a prototype/early version at http://ilbudgetclock.blogspot.com. Right now, it's under my name and is not visible to search engines. I'd like to launch it today under the Chi Hack Night name and start posting to Twitter and FB. That would let us experiment and get feedback, and then this project could continue to work on the next iteration. We can forward it to ilbudgetclock.com when our site is built. 

Does anyone object to me doing that today?

**Comment by derekeder** [comment]
Sounds good to me! I think the more contributions we get to this the better. The effects of this crisis are far-reaching and hard to pin down.

**Comment by cathydeng** [comment]
hey @kwritenow - I also have a prototype up at https://chihacknight.github.io/il-budget-clock/. I'd prefer to use our own site instead of using blogspot, so that we can control all the styling & interactivity.

**Comment by derekeder** [comment]
ah didn't know @cathydeng had gotten so far on the prototype on github. better to focus our efforts there and ditch the blogspot for now.

**Comment by kwritenow** [comment]
I disagree. The blogspot prototype is complete enough to show now. I was using it to talk to friends about the budget crisis last night.

After using Blogspot, I can see we definitely shouldn't be aiming to build something for that platform. The interactions in Cathy's prototype are much more compelling.  I think blogspot's useful until we get further with our site, though.

**Comment by cathydeng** [comment]
we can easily get our own website complete enough to show tomorrow - it took about an hour to put together the clock & interactions & will only take a few mins to update content. it's putting together content that's time consuming, imo.

@derekeder did you buy the domain?

**Comment by derekeder** [comment]
@cathydeng done. DNS is setup and pointing to gh-pages. Go ahead and add the CNAME

**Comment by kwritenow** [comment]
Thanks for taking care of that, @derekeder! 
@cathydeng what's the best way for me to help get content into your prototype? Or do you need me to wait until tomorrow evening? I like to see how some of what's written so far might fit or be tweaked to be a better fit there.

**Comment by cathydeng** [comment]
hm, want to start a google doc & drop in the reasons we have in #15? & drop the google doc link in the issue? then we can collaboratively edit them, & then copy everything from the google doc into the site. would be great to have a source link for each reason.
