### ISSUE TITLE
potentially link to an existing lookup of representatives

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#17]
I was looking for one that won't take forever to load on a phone and doesn't return a long list of all your representatives (if you're looking at a list that includes your Congress members, it can get confusing, I'm thinking).
This one requires pinch and zoom but it's fairly simple: http://il--nea.capwiz.com/nea/il/directory/statedir.tt?state=IL&lvl=state

**Comment by derekeder** [comment]
Open States has this for State House and Senate: http://openstates.org/find_your_legislator/

DataMade is also working on a tool that does this for another project in the coming months.

**Comment by kwritenow** [comment]
Ah, yes, that one's better.

**Comment by hunterowens** [comment]
This is now linked. Although we might want to consider using [jquery-findyourrep](https://github.com/sunlightlabs/jquery-findyourrep)
