### ISSUE TITLE
get feedback from at least three people at Hack Night tonight

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#23]
Let's show the .io prototype to:
- a journalist - DONE
- someone active on Black Twitter, preferably under 24 yrs old
- someone not very active on social media, considers themselves to be politically engaged - DONE

Goals:
- Get feedback from people who are likely to share the app
- Select a call to action
- Refine UI labels and copy to provide the information that is highest priority for users
- Reduce barriers to sharing
- Check for glaring usability issues

Questions for the journalist:
- What do you think are the most important things someone would want to know about this?
- Do you think this will make people more informed about the budget impasse? Why or why not?
- Do you think this will make people more likely to do something about the budget impasse? Why or why not?
- What would make this more informative?
- What would make this more accurate?

Questions for others:
- (let them explore and talk about what they see on the site without giving them any background)
- What does this site seem to be about?
- How would you describe this site to a friend?
- When people share things like this on social media, do you click it? Why or why not?
- Would you share this on social media? Why or why not?
- Which site would you be most likely to share it on? Why?
- Which site would you be least likely to share it on? Why?
- Do you think your friends would like this site? Why or why not?
- What other information would you need before you would feel comfortable sharing this site?
- Do you think people would actually call their representatives after using this site? Why or why not?
- Do you think you would? Would you email or call?
- What other information would you need before you would feel comfortable calling or emailing your representatives?

**Comment by hunterowens** [comment]
Done! 9 people showed up to help build the site!
