### ISSUE TITLE
minor language tweaks

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#24]
1. Opening view should have car chart, and scatter plots
2. Scotland, Wales and N Ireland are not on the text menu.
3. Replace all Instances of “High School” with “School Leavers”
4. When clicking on an occupation in the bar chart, bring up occupation profile light box?
5. Determine how to handle the Nation -> region -> city hierarchy for England
6. Expand y-axes on scatters?
7. Remove y-axis value on Competitiveness? The value’s don’t mean anything
8. Make sure that all y-axis values for competitiveness center on 0 and use a similar scale.
9. Add a blurb about each chart between the title and the chart?
10. Write help/about
11. Add company profiles
12. Add acknowledgment to JPMC as a funder

**Comment by hunterowens** [comment]
This might be a different repo?

**Comment by cathydeng** [comment]
oops too many github tabs
