### ISSUE TITLE
Week 1

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#3]
# Goals
## Find folks who are interested in helping
- Researcher
- Visual/interaction designer
- Additional developer
## Conduct background research to inform our call to action

Find existing data on similar apps, or cross reference data on political engagement, types of social media shares, preferred type of contact with officials, mobile usage

**Comment by cathydeng** [comment]
I don't think we need an additional developer or visual/interaction designer - I can do that. These roles would be helpful for additional related projects tho, for the other ideas you put down in the storymap

**Comment by hunterowens** [comment]
Closing for now.
