### ISSUE TITLE
set up a google form to collect stories

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#32]
this should be among the calls to action. has someone put this together already?

**Comment by hunterowens** [comment]
This doesn't appear done. Should I take a stab at it?

**Comment by cathydeng** [comment]
can you do it in the next hour? if not i'll just do it now

**Comment by hunterowens** [comment]
I should probably go to sleep rn. Was gonna tackle first thing in AM. Go
ahead, then!

**Comment by cathydeng** [comment]
np! go sleep, sleep is good.

**Comment by hunterowens** [comment]
@cathydeng Should I do this now?

**Comment by cathydeng** [comment]
actually yes I never got to it. can you give me access to edit the form & see responses?

**Comment by cathydeng** [comment]
also link to the form from the relevant call to action on the homepage?

**Comment by hunterowens** [comment]
Done and Done

**Comment by cathydeng** [comment]
yay thank you! :sparkles:
