### ISSUE TITLE
Conduct background research to inform our call to action

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#4]
Find existing data on similar apps, or cross reference data on political engagement, types of social media shares, preferred type of contact with officials, mobile usage

**Comment by cathydeng** [comment]
related to #13

**Comment by kwritenow** [comment]
The Borgen Project makes a pretty good case for calling your representatives. http://borgenproject.org/call-congress/

The video reminder they have on their site could fit well with the tone we're developing: https://vimeo.com/50244998

This public interest lobby also says it can be effective to contact reps, but make it personal, individualized. "Before email, most offices heard from about 2 percent of their constituents. Now the figure is closer to 4 percent to 5 percent. The challenge for each office is how to deal with the increased volume of communication in an efficient and meaningful manner."
http://fcnl.org/resources/newsletter/oct07/do_emails_and_letters_to_congress_work/

**Comment by kwritenow** [comment]
Per Pew research (2012), people most likely to share and consume political content on social media are young, liberal, black, and already politically engaged: http://www.pewinternet.org/2012/09/04/politics-on-social-networking-sites/

"
    25% of SNS users say they have become more active in a political issue after discussing it or reading posts about it on the sites.
    16% of SNS users say they have changed their views about a political issue after discussing it or reading posts about it on the sites.
    9% of SNS users say they have become less involved in a political issue after discussing it or reading posts about it on the sites."

They're more likely to see it on Twitter, but they're more likely to post it and comment on Facebook: http://www.journalism.org/2015/07/14/the-evolving-role-of-news-on-twitter-and-facebook/

For those following news via social media, it's at least as likely as not they're doing so on a mobile device: http://www.journalism.org/2013/11/14/news-use-across-social-media-platforms/

People are less likely to share their views if they feel their followers will disagree, so we might should be careful framing suggested posts as opinions, and consider providing in-person opportunities to act.  http://www.pewinternet.org/2014/08/26/social-media-and-the-spiral-of-silence/

People in all demographics are increasingly on social media, but low income and rural people lag behind in usage rates. If we prioritize that audience, we could think of alternatives to social media CTAs. http://www.pewinternet.org/2015/10/08/social-networking-usage-2005-2015/

**Comment by hunterowens** [comment]
Done [for now]
