### ISSUE TITLE
add year position to clock :-(

### ISSUE THREAD

**Issue by derekeder** [chihacknight/il-budget-clock#42]
We're coming up on 1 year with no budget on July 1st, 2016.

The clock will need to be updated to show years in addition to months, days, etc

📉 💸 😢 🕐

**Comment by connorsb** [comment]
Over on the PA Budget Clock, we rewrote the "pull the different times" using the _get_ function, which seems to work a little better, and which also can _get_ the year.

```

            var clock = moment();
            var end = moment("July 1 2016 00:00:00");
            var countdown = moment.duration();
            updateClock();
            setInterval(function(){
                updateClock();
            }, 1000);


            function updateClock(){
                clock = moment();
                countdown = moment.duration(end.diff(clock));
                console.log(countdown);
                $("#months").html(countdown.get('month')); //$("#months").html(clock.get('month'));
                $("#days").html(countdown.get('days')); // $("#days").html(clock.get('date'));
                $("#hours").html(countdown.get('hour'));// $("#hours").html(clock.get('hour'));
                $("#minutes").html(countdown.get('minute'));// $("#minutes").html(clock.get('minute'));
                $("#seconds").html(countdown.get('second')); // $("#seconds").html(clock.get('second'));
            }
```

is the relevant code snippet, though you'll note that our clock is currently counting DOWN to the end of PA's fiscal year.

https://github.com/openpgh/pabudgetclock/blob/gh-pages/_layouts/default.html is the source

**Comment by derekeder** [comment]
thanks @connorsb. I did a little refactoring a few months ago to use the `get` function as well. It's much better! https://github.com/chihacknight/il-budget-clock/blob/master/_layouts/default.html#L97

**Comment by connorsb** [comment]
Adding year should just mean adding it as a variable (in the css), and adding a line in that get part. Today, I'll be working on writing copy for three days from now, when Pennsylvania's budget will, presumably, be overdue... again. Not as bad as y'all have it, but bad.

Also, have you considered adding a second timer (probably just cut-and-paste all but the year-part of the first), because the NEW budget is ALSO overdue?

**Comment by derekeder** [comment]
Oh boy. Well, I think one clock counting how long we haven't had a budget for is enough. And simpler.

**Comment by derekeder** [comment]
Whelp, a temporary stopgap budget was passed today: http://chicago.suntimes.com/news/budget-bills-pass-illinois-house-amid-last-minute-drama/

Going off of the [assessment of Chris Kaergard and his #budgetbeard](https://twitter.com/ChrisKaergard/status/748656969658015745), we will be stopping the clock and posting a message accordingly.

So thankfully, a adding a years position will not be needed.

**Comment by derekeder** [comment]
I ended up doing this anyway in https://github.com/chihacknight/il-budget-clock/commit/9fb7be829ea12d33ce555e21629977b20beaed54
