### ISSUE TITLE
stop the clock

### ISSUE THREAD

**Issue by derekeder** [chihacknight/il-budget-clock#44]
The IL house and senate passed a temporary, 6 month stopgap budget that was signed into law by Gov Rauner on June 30, 2016 at roughly 7pm.

http://chicago.suntimes.com/news/budget-bills-pass-illinois-house-amid-last-minute-drama/

We will freeze the clock to show the time elapsed and post a message accordingly.

Related to #42

**Comment by derekeder** [comment]
Update on time: Gov Rauner's office sent an email indicating the budget was signed at 5:18:29pm

<img width="502" alt="screen shot 2016-06-30 at 9 00 35 pm" src="https://cloud.githubusercontent.com/assets/919583/16509780/eb9e38a2-3f05-11e6-8ccc-376bfda673ae.png">

**Comment by renemarcelo** [comment]
I Wholeheartedly +1 this.

On June 30, 2016, at 9:06 PM, Derek Eder notifications@github.com wrote:

Update on time: Gov Rauner's office sent an email indicating the budget was signed at 5:18:29pm

￼
