### ISSUE TITLE
Find a visual designer :D

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#5]
Need someone to work with Cathy next week on styling the site.

**Comment by easherma** [comment]
I'd be up for this!

**Comment by kwritenow** [comment]
Great! Do you have any availability on Sunday or Monday evening to sketch/compare sketches? I can do some looking for background information before that.

Or , does it work better for you to wait until Tuesday? In person does tend to be a bit easier.

**Comment by easherma** [comment]
Waiting til Tuesday would be best for me!

**Comment by hunterowens** [comment]
I think we're good?

**Comment by hunterowens** [comment]
Thanks @cathydeng @derekeder @easherma !!! Looks Great
