### ISSUE TITLE
Sketch & storyboard

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#6]
Sketch ideas, then storyboard so we kno the flo

**Comment by kwritenow** [comment]
@cathydeng, I'm thinking this needs to happen before or in parallel to start of coding so we know site and page structure. And ideally after sketch/assumption personas.

**Comment by cathydeng** [comment]
I usually integrate design & development, & rapidly prototype through code. I'd like to keep the site structure as simple as possible, one page, maybe two max - just a big fat clock & a blob of content. we can switch up the design of the content later, but it's hard to design that without gathering the content (or deciding what kind of content to include) first, so I think we should prioritize that.

**Comment by kwritenow** [comment]
sounds good

**Comment by hunterowens** [comment]
Site looks good!
