### ISSUE TITLE
Draft assumption personas 

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#7]

**Comment by cathydeng** [comment]
need someone to work w/ @kwritenow (~1 hr, maybe less) to do personas, either next tues or remotely

**Comment by renemarcelo** [comment]
Hi @cathydeng, please what is definition of persona in this context?.  Or is it discussed elsewhere on this project?

On January 21, 2016, at 2:59 PM, Cathy Deng notifications@github.com wrote:

need someone to work w/ @kwritenow (~1 hr, maybe less) to do personas, either next tues or remotely

**Comment by cathydeng** [comment]
hey @renemarcelo! it's an excecise in defining types of people who would be the target audience, to guide development & design

**Comment by kwritenow** [comment]
I've started thinking about some potential differences between users. I'm starting with my own experiences and those of people I know--assumptions. PLEASE feel free to jump in and make some notes based on your own experiences. Links to relevant data are very much welcome, too.

I've made a list of user types based on differences in the roles they play in social services and government. We wouldn't ultimately want this many personas if we fully developed them, but it's a decent place to start. I'm sure this list is not complete. Feel free to add to it. You could also try thinking about them by levels of civic engagement or levels of engagement on social media. I filled out one, and I invite you to add to that or fill out others.

Service consumer
- behaviors: low income and/or youth = more likely to be mobile-only for web access, likely a range of knowledge about resources and procedures so some will search less effectively for help and some will be able to expertly navigate the intricacies of their providers. Perhaps:  <-sporadic engagement <———>persistently investigating options
- attitudes: worry, stress, physical distress, fear for my safety, shame at degradation of quality of life, fight-or-flight, resourcefulness, hustle, anger, burnt out by seeking assistance
- motivations: restore or replace needed services or prevent the loss of services, let people know so they can share in the outrage and help, find information
- ideas/insights: may be too busy or underresourced or overwhelmed to participate in the campaign. or, may appreciate having something they can share to help explain what is happening to them. 
- scenarios: discover the clock randomly while on social media, discover via a search, discover via someone sending it to them directly
- questions: how likely are they to share with fellow consumers? how likely are they to share with their full network? how likely are they to engage with officials directly?

Other citizens
- behaviors: 
- attitudes: 
- motivations: 
- ideas/insights:  
- scenarios: 
- questions: 

Political staffer
- behaviors: 
- attitudes: 
- motivations: 
- ideas/insights:  
- scenarios: 
- questions: 

State legislator
Journalist

**Comment by hunterowens** [comment]
Closing for now, can refer/reopen back if we need to.
