### ISSUE TITLE
Find another researcher

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#8]
Could use some help on assumption personas and background research. No special research skills needed, I don't think. I can guide the personas exercise, just need more input.

**Comment by cathydeng** [comment]
For research, I think research on the content we're presenting is going to be higher priority than research on the audience, since this isn't an app or a tool to solve a particular problem & more of a quick data display project

**Comment by kwritenow** [comment]
I agree on the prioritization, though I'm going to try to get to both. Assumption personas for something this small take ~an hour, will be informed by the research on the issue. Audience relates to where they'll discover the site, where they'll share it, whether they'll share it, other actions they would tend to take, and what they'll want to know about it.

**Comment by cathydeng** [comment]
ya, personas are great. another researcher doesn't hurt, but don't think it's required, since it's a small task.

**Comment by kwritenow** [comment]
It doesn't need to be a researcher, even. The more important this is that it's a group activity, and not just reliant on my input.

**Comment by cathydeng** [comment]
kk I'm gona collapse this issue into #7
